-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  total_kilos numeric default 0,
  notes text
);

-- Create order_items table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_name text not null,
  quantity integer not null,
  kilos_per_unit numeric not null,
  total_item_kilos numeric not null,
  lot_number text,
  is_box boolean default false
);

-- Enable Row Level Security (RLS)
alter table orders enable row level security;
alter table order_items enable row level security;

-- Create policies to allow public access (for simplicity in this demo)
-- WARNING: In a production app with auth, you should restrict this to authenticated users
create policy "Public orders access" on orders for all using (true);
create policy "Public items access" on order_items for all using (true);
